### PR TITLE
Improve afu-vicmd

### PR DESCRIPTION
**Pull request by aiya000**
~~(This PR depends [prev PR](https://github.com/hchbaw/auto-fu.zsh/pull/44), please accept it first)~~ It was reverted 🙇 

I improved afu-vicmd keymaps 😄

### CODE REVIEW

**Comment by aiya000** [comment]
That commit (#44) was reverted !

**Comment by hchbaw** [comment]
Thank you very much!

I'm not 100% sure why these vi-cmd specific keybinds should be explicitly defined. I don't do it like this, but when I press say an `i` in the normal-mode then the `afu` keymap will be successfully activated.

I suspect that you might be missing the “`zle -N zle-keymap-select auto-fu-zle-keymap-select`”.
Please add it in your `~/.zshrc`.
If you have customized the `zle-keymap-select`, please add `auto-fu-zle-keymap-select "$@"` (Don't forget the last `"$@"` in this case, please).

**Comment by aiya000** [comment]
Thanks !

mmm..., I want to another way of `zle -N zle-keymap-select auto-fu-zle-keymap-select` :(  
Because ...

1. into afu
2. leave afu by `afu+vi-cmd-mode` (and go to `afu-vicmd`)
3. input `a` (or `i`, `A`, `I`)

I return to the `main` if I executed this,  
but I want to return to `afu`.

**Comment by aiya000** [comment]
And I think this way should be given with `afu+vi-cmd-mode` by official :smiley:

**Comment by hchbaw** [comment]
Sorry, I might misunderstand your case, so I would like to reconfirm.

It seems that the `zle -N zle-keymap-select auto-fu-zle-keymap-select` is the problem.

If I have it, I return to `afu` when pressing `a` in the normal-mode. And this is the right behavior but...
If I don't have it, I return to `main`. It is not right.

So, my questions is: Why you cannot have it in the `~/.zshrc`?

PS: If you customize `zle-keymap-select`, you could do the following:

    function zle-keymap-select () {
      # some codes here
      # ...
      auto-fu-zle-keymap-select "$@" # Please add this somewhere, don't forget the last "$@".
      # ...
    }
    zle -N zle-keymap-select

**Comment by aiya000** [comment]
```sh
function zle-keymap-select () {
	afu+vi-ins-mode-i () { zle -K afu;                            }; zle -N afu+vi-ins-mode-i
	afu+vi-ins-mode-I () { zle -K afu; CURSOR=0;                  }; zle -N afu+vi-ins-mode-I
	afu+vi-ins-mode-a () { zle -K afu; CURSOR=$(( $CURSOR + 1 )); }; zle -N afu+vi-ins-mode-a
	afu+vi-ins-mode-A () { zle -K afu; CURSOR=${#BUFFER};         }; zle -N afu+vi-ins-mode-A
	afu+vi-ins-mode-s () { zle -K afu; BUFFER="${LBUFFER}${RBUFFER[2, $#RBUFFER]}"; }; zle -N afu+vi-ins-mode-s
	afu+vi-ins-mode-S () { zle -K afu; BUFFER='';                 }; zle -N afu+vi-ins-mode-S
	afu+vi-ins-mode-C () { zle -K afu; BUFFER="${LBUFFER}";       }; zle -N afu+vi-ins-mode-C
	auto-fu-zle-keymap-select "$@"
}
zle -N zle-keymap-select
```

This worked rightly, Thanks :smiley:
But ...

This PR's reason is simply, for the `user friendly`.  
I think ... if auto-fu.zsh provides `afu-vicmd`,
auto-fu.zsh should provide the cross road of between `afu` and `afu-vicmd`.

This is the reason of that I think this way shouldn't be written in `.zshrc` ...

If got it, the `vicmd` users can install this more easily !

**Comment by hchbaw** [comment]
:bowing_man: :bowing_man: :bowing_man: I have a question, sorry again.

I would like to know whether it could work right if you delete the below codes from the above `zle-keymap-select` function :thinking: 

```sh
	afu+vi-ins-mode-i () { zle -K afu;                            }; zle -N afu+vi-ins-mode-i
	afu+vi-ins-mode-I () { zle -K afu; CURSOR=0;                  }; zle -N afu+vi-ins-mode-I
	afu+vi-ins-mode-a () { zle -K afu; CURSOR=$(( $CURSOR + 1 )); }; zle -N afu+vi-ins-mode-a
	afu+vi-ins-mode-A () { zle -K afu; CURSOR=${#BUFFER};         }; zle -N afu+vi-ins-mode-A
	afu+vi-ins-mode-s () { zle -K afu; BUFFER="${LBUFFER}${RBUFFER[2, $#RBUFFER]}"; }; zle -N afu+vi-ins-mode-s
	afu+vi-ins-mode-S () { zle -K afu; BUFFER='';                 }; zle -N afu+vi-ins-mode-S
	afu+vi-ins-mode-C () { zle -K afu; BUFFER="${LBUFFER}";       }; zle -N afu+vi-ins-mode-C
```

So my questions is, if you put the below codes, does it work right?

```sh
function zle-keymap-select () {
  auto-fu-zle-keymap-select "$@"
}
zle -N zle-keymap-select
# This is same as the below:
# zle -N zle-keymap-select auto-fu-zle-keymap-select
```


----

PS:
As you can see, I'm a `vicmd` user, too.
Somehow I don't need to modify the `afu-vicmd` keybindings that you are suggesting.
I have a quite simple `.zshrc`:

```sh
echok () {
  echo "\n***${KEYMAP}***"
  zle reset-prompt
}
zle -N echok
bindkey '^X^X' echok
bindkey -M vicmd '^X' echok


source ~/c/auto-fu.zsh/auto-fu.zsh # Sorry hard coding
zle -N zle-line-init auto-fu-init
zle -N zle-keymap-select auto-fu-zle-keymap-select
bindkey -M afu '^[^[' afu+vi-cmd-mode
```
With this `.zshrc`, it works right for me:
1. into `afu`
2. leave `afu` by `afu+vi-cmd-mode` (and go to `afu-vicmd`)
    (I pressed <kbd>ESC</kbd>-<kbd>ESC</kbd>)
3. input <kbd>a</kbd> (or <kbd>i</kbd>, <kbd>A</kbd> <kbd>I</kbd>)
4. return to `afu` (not `main` as you had encountered)
   (I pressed <kbd>CTRL</kbd>-<kbd>X</kbd>, <kbd>CTRL</kbd>-<kbd>X</kbd> to confirm)

The purpose of the function `auto-fu-zle-keymap-select` is to coodinate the `afu <-> afu-vicmd` keymap transitions if it works right.

**Comment by hchbaw** [comment]
↑ I did this without your patch, I did it on the `master` branch.
Sorry, it is not clear enough about my environment :bowing_man:

**Comment by aiya000** [comment]
Oh ?  
But `zle -N zle-keymap-select auto-fu-zle-keymap-select` is worked correctly without `improve_afu_vicmd` !
(i, a, I and A returns to afu !)

Sorry, I misunderstood `zle -N zle-keymap-select auto-fu-zle-keymap-select`...

Thanks for giving auto-fu.zsh, auto-fu.zsh is great :smile:

**Pull request closed without merging**
